// <auto-generated />
using System;
using BRS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BRS.Migrations
{
    [DbContext(typeof(BRSDbContext))]
    [Migration("20240404173002_Add_FK")]
    partial class Add_FK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BRS.Entities.BookRental", b =>
                {
                    b.Property<Guid>("RentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BookDate")
                        .HasColumnType("date");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("RentDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RentId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BookRental");
                });

            modelBuilder.Entity("BRS.Entities.BookStatus", b =>
                {
                    b.Property<Guid>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bk_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.HasKey("StatusId");

                    b.ToTable("BookStatus");
                });

            modelBuilder.Entity("BRS.Entities.Books", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bk_Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bk_Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bk_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bk_Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bk_Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.HasKey("BookId");

                    b.HasIndex("StatusId")
                        .IsUnique();

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BRS.Entities.Inventory", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableBooks")
                        .HasColumnType("integer");

                    b.Property<int>("ReservedBooks")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBooks")
                        .HasColumnType("integer");

                    b.HasKey("InventoryId");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("BRS.Entities.RentHistory", b =>
                {
                    b.Property<Guid>("RentHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RentId")
                        .HasColumnType("uuid");

                    b.HasKey("RentHistoryId");

                    b.HasIndex("RentId");

                    b.ToTable("RentHistory");
                });

            modelBuilder.Entity("BRS.Entities.Roles", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BRS.Entities.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BRS.Entities.BookRental", b =>
                {
                    b.HasOne("BRS.Entities.Books", "Books")
                        .WithMany("BookRental")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BRS.Entities.Users", "Users")
                        .WithOne("BookRental")
                        .HasForeignKey("BRS.Entities.BookRental", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Books");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BRS.Entities.Books", b =>
                {
                    b.HasOne("BRS.Entities.BookStatus", "BookStatus")
                        .WithOne("Books")
                        .HasForeignKey("BRS.Entities.Books", "StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookStatus");
                });

            modelBuilder.Entity("BRS.Entities.RentHistory", b =>
                {
                    b.HasOne("BRS.Entities.BookRental", "BookRental")
                        .WithMany("RentHistory")
                        .HasForeignKey("RentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookRental");
                });

            modelBuilder.Entity("BRS.Entities.Users", b =>
                {
                    b.HasOne("BRS.Entities.Roles", "Roles")
                        .WithOne("Users")
                        .HasForeignKey("BRS.Entities.Users", "RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("BRS.Entities.BookRental", b =>
                {
                    b.Navigation("RentHistory");
                });

            modelBuilder.Entity("BRS.Entities.BookStatus", b =>
                {
                    b.Navigation("Books")
                        .IsRequired();
                });

            modelBuilder.Entity("BRS.Entities.Books", b =>
                {
                    b.Navigation("BookRental");
                });

            modelBuilder.Entity("BRS.Entities.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BRS.Entities.Users", b =>
                {
                    b.Navigation("BookRental")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
